---
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'output/**/*'
  TargetRubyVersion: 2.4

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'configs/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

# Excluding 'configs/platforms/*' so rubocop ignores the platforms that just 
# inherit from default. 
Style/SymbolProc:
  Enabled: true
  Exclude:
    - 'configs/platforms/*'

Style/StringLiterals:
  Enabled: true
  Exclude:
    - 'configs/platforms/*'
